### ISSUE TITLE
TZNames.GetAbbreviationsForTimeZone() for 'nb-NO' throws System.Exception: Could not find a language with code nb-NO

### ISSUE THREAD

**Issue by linusswanbergpolestar** [mattjohnsonpint/TimeZoneNames#75]
Happens for versions 5.0.0 and 5.0.1

Works fine for version 4.2.0

**Comment by mattjohnsonpint** [comment]
Hmmm.. I'll have to investigate further.  Thanks.

**Comment by JSCProjects** [comment]
We have got the same issues

**Comment by mattjohnsonpint** [comment]
Indeed, this is still happening on 6.0.0.  

```csharp
var results = TimeZoneNames.TZNames.GetNamesForTimeZone("America/Los_Angeles", "nb-NO");
Console.WriteLine(results.Generic);
```

```
Unhandled exception. System.Exception: Could not find a language with code nb-NO
   at TimeZoneNames.TZNames.GetLanguageKey(String languageCode, Boolean forDisplayNames)
   at TimeZoneNames.TZNames.GetNamesForTimeZone(String timeZoneId, String languageCode)
   at Program.<Main>$(String[] args) in Program.cs:line 1
```

**Comment by bmrfvr** [comment]
I believe this issue would be fixed by my PR: https://github.com/mattjohnsonpint/TimeZoneNames/pull/104

**Comment by mattjohnsonpint** [comment]
Unfortunately, `nb` is not a supported CLDR languages, so I can't do anything about this.

See my comments here: https://github.com/mattjohnsonpint/TimeZoneNames/issues/108#issuecomment-2627992060
